[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  targetPort = 5173
  publish = "dist"
[[redirects]]
  from = "/apps/"
  to = "/apps/index.html"
  status = 200
